export type Track = {
  id: string;
  title: string;
  artist: string;
  film: string;
  year: string;
  duration: number; // in seconds
  videoId: string;
};

export const playlists: Record<string, Track[]> = {
  "Playlist 1": [
    {
      id: "1",
      title: "'Sooraj Dooba Hain' FULL VIDEO SONG | Arijit singh Aditi Singh Sharma | T-SERIES",
      artist: "T-Series",
      film: "Unknown",
      year: "Unknown",
      duration: 248,
      videoId: "nJZcbidTutE",
    },
    {
      id: "2",
      title: "Nashe Si Chadh Gayi | Full Song | Befikre, Ranveer Singh, Vaani Kapoor, Arijit Singh, Vishal-Shekhar",
      artist: "YRF",
      film: "Unknown",
      year: "Unknown",
      duration: 228,
      videoId: "HoCwa6gnmM0",
    },
    {
      id: "3",
      title: "A.R. Rahman - Barso Re (Lyric Video)",
      artist: "SonyMusicIndiaVEVO",
      film: "Unknown",
      year: "Unknown",
      duration: 285,
      videoId: "B1dmwRBVqWI",
    },
    {
      id: "4",
      title: "Khud Se Pyar by Ashwani Gupta (Official Music Video)",
      artist: "Ashwani Gupta",
      film: "Unknown",
      year: "Unknown",
      duration: 282,
      videoId: "pfVfhRSVIRc",
    },
    {
      id: "5",
      title: "The Breakup Song - Full Video | Ranbir, Anushka | Arijit, Badshah, Jonita, Nakash | Pritam | ADHM",
      artist: "Sony Music India",
      film: "Unknown",
      year: "Unknown",
      duration: 212,
      videoId: "kd5KqlmcHNo",
    },
    {
      id: "6",
      title: "Lyrical: Yeh Ishq Hai | Jab We Met | Kareena Kapoor, Shahid Kapoor | Pritam | Shreya Ghoshal",
      artist: "T-Series",
      film: "Unknown",
      year: "Unknown",
      duration: 297,
      videoId: "b_sCZbYyuO4",
    },
    {
      id: "7",
      title: "Piya O Re Piya Lyrical - Tere Naal Love Ho Gaya | Riteish Deshmukh, Genelia | Atif Aslam, Shreya",
      artist: "Tips Official",
      film: "Unknown",
      year: "Unknown",
      duration: 310,
      videoId: "u-FaTNxrWhw",
    },
    {
      id: "8",
      title: "Mitwa - Full Video | Shahrukh Khan | Rani Mukherjee | Shafqat Amanat Ali | Shankar Mahadevan | KANK",
      artist: "Sony Music India",
      film: "Unknown",
      year: "Unknown",
      duration: 361,
      videoId: "ru_5PA8cwkE",
    },
    {
      id: "9",
      title: "Bol Na Halke Halke | Full Song | Jhoom Barabar Jhoom | Abhishek, Preity | Shankar-Ehsaan-Loy, Gulzar",
      artist: "YRF",
      film: "Unknown",
      year: "Unknown",
      duration: 462,
      videoId: "jXwg9l9D51A",
    },
    {
      id: "10",
      title: "MATARGASHTI full VIDEO Song | TAMASHA Songs 2015 | Ranbir Kapoor, Deepika Padukone | T-Series",
      artist: "T-Series",
      film: "Unknown",
      year: "Unknown",
      duration: 266,
      videoId: "6vKucgAeF_Q",
    },
    {
      id: "11",
      title: "Ilahi Full Video Song | Yeh Jawaani Hai Deewani | Ranbir Kapoor, Deepika Padukone | Pritam",
      artist: "T-Series",
      film: "Unknown",
      year: "Unknown",
      duration: 204,
      videoId: "fdubeMFwuGs",
    },
    {
      id: "12",
      title: "SANAM - Hai Apna Dil To Awara - Ft. Soogum Sookha",
      artist: "Sanam",
      film: "Unknown",
      year: "Unknown",
      duration: 206,
      videoId: "JlgkMXex2DI",
    },
    {
      id: "13",
      title: "Kashmir Main Tu Kanyakumari(Lyrical)|Chennai Express |Shahrukh K, Deepika P,Sunidhi C,Arijit S,Neeti",
      artist: "T-Series",
      film: "Unknown",
      year: "Unknown",
      duration: 327,
      videoId: "WxtJqyIyThU",
    },
    {
      id: "14",
      title: "A.R. Rahman - Tum Tak (Lyric Video) | Raanjhanaa | A. R. Rahman | Dhanush | Sonam Kapoor | Javed Ali",
      artist: "Sony Music India",
      film: "Unknown",
      year: "Unknown",
      duration: 304,
      videoId: "AGsn2ycFRqI",
    },
    {
      id: "15",
      title: "Drama Queen Full Video - Hasee Toh Phasee | Parineeti, Sidharth | Shreya Ghoshal | Karan Johar",
      artist: "SonyMusicIndiaVEVO",
      film: "Unknown",
      year: "Unknown",
      duration: 199,
      videoId: "0Qs-Suk42dY",
    },
    {
      id: "16",
      title: "'Love is a Waste of Time' FULL VIDEO SONG | PK | Aamir Khan | Anushka Sharma | T-series",
      artist: "T-Series",
      film: "Unknown",
      year: "Unknown",
      duration: 257,
      videoId: "jAmzBv3oq8M",
    },
    {
      id: "17",
      title: "Prem Ki Naiyya - Ajab Prem Ki Ghazab Kahani | Ranbir Kapoor, Katrina | Neeraj, Suzanne | Pritam",
      artist: "Tips Official",
      film: "Unknown",
      year: "Unknown",
      duration: 210,
      videoId: "J3Ux5TQ4oUc",
    },
    {
      id: "18",
      title: "Iktara- a tribute to Amit Trivedi | Istoria In-Sync 5.0 | The LIVE 100 Experience",
      artist: "Istoria XIC",
      film: "Unknown",
      year: "Unknown",
      duration: 268,
      videoId: "vLA2YPTqOv4",
    },
    {
      id: "19",
      title: "Jiya Re Song | Jab Tak Hai Jaan | Shah Rukh Khan | Anushka | Neeti Mohan | A. R. Rahman",
      artist: "YRF",
      film: "Unknown",
      year: "Unknown",
      duration: 133,
      videoId: "xdOumVBRKp8",
    },
    {
      id: "20",
      title: "Dooriyan",
      artist: "Pritam",
      film: "Unknown",
      year: "Unknown",
      duration: 338,
      videoId: "OiqiOKyeO8A",
    },
    {
      id: "21",
      title: "JAB TAK Full Video | M.S. DHONI -THE UNTOLD STORY | Armaan Malik, Amaal Mallik |Sushant Singh Rajput",
      artist: "T-Series",
      film: "Unknown",
      year: "Unknown",
      duration: 211,
      videoId: "K-Ts-NFR62o",
    },
    {
      id: "22",
      title: "\"Subhanallah\"  Full Video Song | Yeh Jawaani Hai Deewani | Pritam | Ranbir Kapoor, Deepika Padukone",
      artist: "T-Series",
      film: "Unknown",
      year: "Unknown",
      duration: 206,
      videoId: "QYO6AlxiRE4",
    },
    {
      id: "23",
      title: "Tum Jo Aaye (Reprise)",
      artist: "Pritam",
      film: "Unknown",
      year: "Unknown",
      duration: 268,
      videoId: "0PddlwK7qtg",
    },
    {
      id: "24",
      title: "Tera Deedar Hua (From The Heart) - Lyrical Video | Emraan Hashmi | Esha Gupta | Javed Ali | Jannat 2",
      artist: "Sony Music India",
      film: "Unknown",
      year: "Unknown",
      duration: 347,
      videoId: "5jOqWOZTusg",
    },
    {
      id: "25",
      title: "Yeh Dil Deewana | Shah Rukh Khan | Sonu Nigam | Nadeem-Shravan | Pardes",
      artist: "Golden Hits",
      film: "Unknown",
      year: "Unknown",
      duration: 385,
      videoId: "_4Ft9UIKzwk",
    },
  ]
};
